fixing stats page
wasade/qiita pull request #1
Opened 2019-07-31 15:38 UTC by antgonza

2019-07-31 19:49 UTC, wasade requested changes
Thanks! A few mostly minor comments or questions

2019-07-31 19:49 UTC, wasade commented on qiita_db/meta_util.py
> +    per_data_type_stats = defaultdict(lambda: 0)
Usually I've seen this as: `per_data_type_stats = defaultdict(int)`

2019-07-31 19:49 UTC, wasade commented on qiita_db/meta_util.py
> +            number_studies['sandbox'] += 1
I don't think we want to count complete empty studies, right...? Many of those are presumably just dead ends from people screwing around

2019-07-31 19:49 UTC, wasade commented on qiita_db/meta_util.py
> +        len_samples_ebi = len([
A little more succinct: `len_samples_ebi = sum([esa is not None for esa in st.ebi_sample_accessions.values()])`

2019-07-31 19:49 UTC, wasade commented on qiita_db/meta_util.py
> +            number_samples_ebi_prep += len(
This summing over the same type of structure is done twice, maybe decompose?

2019-07-31 19:49 UTC, wasade commented on qiita_db/meta_util.py
> +        number_of_samples['sandbox'] += len(samples)
If a sample is not associated with a preparation, should it be counted? That implies there isn't physical specimen (from the perspective of qiita)

2019-07-31 19:49 UTC, wasade commented on qiita_db/meta_util.py
> +                    stats.append(
Can this be done outside of the try / except?

2019-07-31 19:49 UTC, wasade commented on qiita_db/meta_util.py
> +        if ft in group_other:
It would be beneficial for `group_other` to be a `set`

2019-07-31 19:49 UTC, wasade commented on qiita_db/study.py
> +            for id_ in qdb.sql_connection.TRN.execute_fetchflatten():
Shouldn't the results of `qdb.sql_connection.TRN.execute_fetchflatten()` be collected within the `TRN` context, and then `yield` the studies outside of the `TRN` context? As is, this would hold the transaction open, possibly indefinitely if `StopGenerator` is never raised

2019-07-31 19:49 UTC, wasade commented on qiita_db/test/test_meta_util.py
> +            ('per_data_type_stats', {b'18S': b'54'}, r_client.hgetall)]
Just so I understand, there are two `18S` preps in the test study, each have the same 27 samples?

2019-07-31 22:04 UTC, antgonza reviewed
@wasade, thanks for review!

2019-07-31 22:04 UTC, antgonza commented on qiita_db/meta_util.py
> +    per_data_type_stats = defaultdict(lambda: 0)
Do you want me to change it? BTW my concern is making sure it's initialized at 0 ...

2019-07-31 22:04 UTC, antgonza commented on qiita_db/meta_util.py
> +            number_studies['sandbox'] += 1
I think even if they are dead, they are in the DB and should be counted, but happy to remove. BTW we do cleanups every 6 months or so ...

2019-07-31 22:04 UTC, antgonza commented on qiita_db/meta_util.py
> +        len_samples_ebi = len([
Thanks, just to be sure; do you want me to change? Your version is 5 chars shorter but perhaps I'm missing something ...

2019-07-31 22:04 UTC, antgonza commented on qiita_db/meta_util.py
> +            number_samples_ebi_prep += len(
What do you mean? Could you point the other line?

2019-07-31 22:04 UTC, antgonza commented on qiita_db/meta_util.py
> +        number_of_samples['sandbox'] += len(samples)
I think so as it's in the DB but again happy to remove ...  Note that this are sandbox samples so IMOO it's fine to count them without preparation.

2019-07-31 22:04 UTC, antgonza commented on qiita_db/meta_util.py
> +                    stats.append(
Yup, will change.

2019-07-31 22:04 UTC, antgonza commented on qiita_db/study.py
> +            for id_ in qdb.sql_connection.TRN.execute_fetchflatten():
Good question, not sure! Any suggestions on how to verify? Note that I thought that the idea of creating the generator is to not store the full list in memory but we could create the list of ids, store that, then loop over that list and yield those Study objects. What do you think?

2019-07-31 22:04 UTC, antgonza commented on qiita_db/test/test_meta_util.py
> +            ('per_data_type_stats', {b'18S': b'54'}, r_client.hgetall)]
That is correct! However, now that you ask, that code is counting all preps and perhaps we should only count public; what do you think?

2019-07-31 22:55 UTC, wasade commented on qiita_db/meta_util.py
> +    per_data_type_stats = defaultdict(lambda: 0)
Given how this is used, I think the `Counter` may be better suited actually

2019-07-31 22:55 UTC, wasade commented on qiita_db/meta_util.py
> +            number_studies['sandbox'] += 1
It depends on the purpose of the count. If the count is intended to convey what we believe to be actual studies (which is what I believe is the goal), then we should not count these as a study without samples is not a study as there is nothing being studied.

2019-07-31 22:55 UTC, wasade commented on qiita_db/meta_util.py
> +        len_samples_ebi = len([
The present comprehension obfuscates the purpose as the subject and predicate come at the end rather than being placed first. Its similar to placing the subject of a sentence at the end rather than upfront.

Restated, I thought it was hard to read and had to stare at it for a while to figure out what was going on.

2019-07-31 22:55 UTC, wasade commented on qiita_db/meta_util.py
> +            number_samples_ebi_prep += len(
line 195

2019-07-31 22:55 UTC, wasade commented on qiita_db/meta_util.py
> +        number_of_samples['sandbox'] += len(samples)
Same argument as the study: if not in a preparation then from the perspective of qiita there is no physical specimen

2019-07-31 22:55 UTC, wasade commented on qiita_db/meta_util.py
> +                    stats.append(
Thanks

2019-07-31 22:55 UTC, wasade commented on qiita_db/study.py
> +            for id_ in qdb.sql_connection.TRN.execute_fetchflatten():
Not closing resources can lead to obscure bugs while also increasing artificial load on the system. This scenario is analogous to not closing files: it is a bad practice particularly for long running processes. 

Please simply move the generator out of the context.

2019-07-31 22:55 UTC, wasade commented on qiita_db/test/test_meta_util.py
> +            ('per_data_type_stats', {b'18S': b'54'}, r_client.hgetall)]
It depends on what is trying to be conveyed to the user. Restricting to public makes sense

2019-08-01 14:34 UTC, antgonza commented on qiita_db/meta_util.py
> +            number_samples_ebi_prep += len(
line 195 is counting the samples in the sample information file (st. ebi_sample_accessions) and here we are counting samples in the prep (pt.ebi_experiment_accessions, experiments as EBI-ENA calls them) ... I'm also updating this line to use the same comprehension list than above

2019-08-05 16:22 UTC, merged